name: HTML5 Build Failure Bug Report
description: Report fails/errors which only happen when building your projects for HTML5 (if other targets do the same, then report this on GameMaker-Bugs site instead)
type: 'Build Bug'
labels: ["gms2","HTML5"]
projects: ["YoYoGames/17"]
body:
  - type: markdown
    attributes:
      value: |
        Search for existing reports for this bug first! If a report already exists, DO NOT send another report now - just leave a thumbs-up/comment on the other report instead.
       
        Most fields need to be filled-in before you can click Submit, as everything is required information for us to confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: What is the bug?
      description: Write a thorough description of the issue. You may paste screenshots and links at suitable locations in your text. (However, DO NOT add a web link and assume we will read an external discussion and guess at the bug ourselves - we will simply close the report.)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue (add as many steps into the gaps below as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
        
  - type: dropdown
    id: version
    attributes:
      label: Which version(s) of GameMaker are you reporting this issue for?
      description: If you are on an older version than the latest version of each install type shown below, install the latest public LTS/Beta version and confirm your issue still exists before you report anything! If you are using a Beta, please also add the full version number into your Description text above.
      multiple: true
      options:
        - 2026.0.0 LTS
        - 2026.100 Betas
        - 2024.14.4 Monthly
        - 2022.0.3 LTS
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Which operating system(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows 11
        - Windows 10
        - macOS Tahoe
        - macOS Sequoia
        - macOS Sonoma
        - macOS Ventura
        - Ubuntu 24 LTS
        - ChromeOS
    validations:
      required: false  

  - type: input
    id: sample
    attributes:
      label: Sample Package
      description: A bug package file is essential for all build reports. Please recreate the problem and then use the Help > Upload a Bug Sample tool inside GameMaker. We recommend you say yes to including your project. Then paste the download URL into the box below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
